### ISSUE TITLE
Support for Aurora 2.x and MySQL 5.7.x

### ISSUE THREAD

**Issue by cdelgadob** [cfn-modules/rds-aurora-serverless#14]
As described here: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.2045.html

Aurora MySQL 2.04.5 is generally available, and enables MySQL engine 5.7 which includes several features.

**Comment by michaelwittig** [comment]
Unfortunately, RDS Aurora Serverless only supports 5.6 at the moment not the whole range that RDS Aurora offers.
